# The Docker image that will be used to build your app
image: node:latest
before_script:
  - npm i -g firebase-tools

prod-hosting:
  stage: deploy
  script:
    - npm build
    - firebase deploy --token $FIREBASE_TOKEN
  environment:
    name: production
    url: https://files-for-freedom.web.app/
